### PR TITLE
Fix build with template-haskell-2.11

### LINKED ISSUE #11: Support for template-haskell 2.11
Below is the compile error with GHC 8, see also https://ghc.haskell.org/trac/ghc/wiki/Migration/8.0#template-haskell-2.11.0.0

```
[1 of 1] Compiling Data.Vector.Unboxed.Deriving ( Data/Vector/Unboxed/Deriving.hs, dist/dist-sandbox-9cffbab4/build/Data/Vector/Unboxed/Deriving.o )

Data/Vector/Unboxed/Deriving.hs:117:14: error:
    • Couldn't match expected type ‘Maybe Kind’ with actual type ‘Con’
    • In the fourth argument of ‘NewtypeInstD’, namely
        ‘(NormalC
            mvName [(NotStrict, ConT ''MVector `AppT` s `AppT` rep)])’
      In the expression:
        NewtypeInstD
          []
          ''MVector
          [s, typ]
          (NormalC mvName [(NotStrict, ConT ''MVector `AppT` s `AppT` rep)])
          []
      In an equation for ‘newtypeMVector’:
          newtypeMVector
            = NewtypeInstD
                []
                ''MVector
                [s, typ]
                (NormalC mvName [(NotStrict, ConT ''MVector `AppT` s `AppT` rep)])
                []

Data/Vector/Unboxed/Deriving.hs:117:31: error:
    Data constructor not in scope: NotStrict :: Bang

Data/Vector/Unboxed/Deriving.hs:117:80: error:
    • Couldn't match expected type ‘Con’ with actual type ‘[t0]’
    • In the fifth argument of ‘NewtypeInstD’, namely ‘[]’
      In the expression:
        NewtypeInstD
          []
          ''MVector
          [s, typ]
          (NormalC mvName [(NotStrict, ConT ''MVector `AppT` s `AppT` rep)])
          []
      In an equation for ‘newtypeMVector’:
          newtypeMVector
            = NewtypeInstD
                []
                ''MVector
                [s, typ]
                (NormalC mvName [(NotStrict, ConT ''MVector `AppT` s `AppT` rep)])
                []

Data/Vector/Unboxed/Deriving.hs:138:14: error:
    • Couldn't match expected type ‘Maybe Kind’ with actual type ‘Con’
    • In the fourth argument of ‘NewtypeInstD’, namely
        ‘(NormalC vName [(NotStrict, ConT ''Vector `AppT` rep)])’
      In the expression:
        NewtypeInstD
          []
          ''Vector
          [typ]
          (NormalC vName [(NotStrict, ConT ''Vector `AppT` rep)])
          []
      In an equation for ‘newtypeVector’:
          newtypeVector
            = NewtypeInstD
                []
                ''Vector
                [typ]
                (NormalC vName [(NotStrict, ConT ''Vector `AppT` rep)])
                []

Data/Vector/Unboxed/Deriving.hs:138:30: error:
    Data constructor not in scope: NotStrict :: Bang

Data/Vector/Unboxed/Deriving.hs:138:69: error:
    • Couldn't match expected type ‘Con’ with actual type ‘[t1]’
    • In the fifth argument of ‘NewtypeInstD’, namely ‘[]’
      In the expression:
        NewtypeInstD
          []
          ''Vector
          [typ]
          (NormalC vName [(NotStrict, ConT ''Vector `AppT` rep)])
          []
      In an equation for ‘newtypeVector’:
          newtypeVector
            = NewtypeInstD
                []
                ''Vector
                [typ]
                (NormalC vName [(NotStrict, ConT ''Vector `AppT` rep)])
                []

Data/Vector/Unboxed/Deriving.hs:151:11: error:
    • Couldn't match expected type ‘Dec’ with actual type ‘Cxt -> Dec’
    • Probable cause: ‘newtypeMVector’ is applied to too few arguments
      In the expression: newtypeMVector
      In the first argument of ‘return’, namely
        ‘[InstanceD cxts (ConT ''Unbox `AppT` typ) [], newtypeMVector,
          instanceMVector, newtypeVector, ....]’
      In a stmt of a 'do' block:
        return
          [InstanceD cxts (ConT ''Unbox `AppT` typ) [], newtypeMVector,
           instanceMVector, newtypeVector, ....]

Data/Vector/Unboxed/Deriving.hs:152:11: error:
    • Couldn't match expected type ‘Dec’ with actual type ‘Cxt -> Dec’
    • Probable cause: ‘newtypeVector’ is applied to too few arguments
      In the expression: newtypeVector
      In the first argument of ‘return’, namely
        ‘[InstanceD cxts (ConT ''Unbox `AppT` typ) [], newtypeMVector,
          instanceMVector, newtypeVector, ....]’
      In a stmt of a 'do' block:
        return
          [InstanceD cxts (ConT ''Unbox `AppT` typ) [], newtypeMVector,
           instanceMVector, newtypeVector, ....]
xcabal: Error: some packages failed to install:
vector-th-unbox-0.2.1.3 failed during the building phase. The exception was:
ExitFailure 1
```

### PR DESCRIPTION
**Pull request by RyanGlScott**
GHC 8.0 (specifically, `template-haskell-2.11.0.0`) introduces some breaking API changes, so this PR uses CPP to get around them. Fixes #11.

### CODE REVIEW

**Comment by hvr** [comment]
@liyang *bump* we'd need a GHC8 compatible package as important packages such as `criterion` depend on this...

**Comment by 23Skidoo** [comment]
Bumpy bump.

**Comment by 23Skidoo** [comment]
Travis failure is spurious, build just needs to be restarted.

**Comment by hvr** [comment]
NMU'ed via http://hackage.haskell.org/package/vector-th-unbox-0.2.1.4

**Comment by hvr** [comment]
@RyanGlScott this PR is obsoleted by #14, please close this one to avoid confusion
